name: Build without tests

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup JDK
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with: 
          java-version: '17'
          distribution: 'zulu'

      # Build
      - name: Build with Gradle
        run: ./gradlew build --exclude-task test
