name: Daily Build and Test

on:
  schedule:
   # - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
    - cron:  '15 15 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup JDK
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run API tests
        run: ./gradlew test --tests epam.api.*
        env:
          token: ${{ secrets.token }}
      - name: Run UI tests
        run: ./gradlew test --tests epam.ui.*
        env:
          testUsername: ${{ secrets.TEST_USER_NAME }}
          testPassword: ${{ secrets.TEST_USER_PASSWORD }}
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: build/reports/tests/
