# This is a basic workflow to help you get started with Actions

name: Run all API tests with sonar

# Controls when the workflow will run
on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'zulu'
      # Build
      - name: Build with Gradle
        run: ./gradlew build --exclude-task test

      - name: Build notification
        uses: FreEZer00/teams-webhook-action@v1.4.1
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: 'Build is finished'
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          additional_button_title: |-
            Link to all runs
          additional_button_url: |-
            https://github.com/PolinaPanarina/ATMPA/actions/workflows/runApiTests.yml
            
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'zulu'

      # Start Test Run Notification
      - name: Start Test Run Notification
        uses: FreEZer00/teams-webhook-action@v1.4.1
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: 'API tests run started'
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          additional_button_title: |-
            Link to all runs
          additional_button_url: |-
            https://github.com/PolinaPanarina/ATMPA/actions/workflows/runApiTests.yml

      - name: Run API tests
        run: ./gradlew test --tests epam.api.* -Drp.endpoint=https://reportportal.epam.com -Drp.api.key=$RP_TOKEN -Drp.launch=Run_API_Tests -Drp.project=polina_panarina_personal_1 -Drp.enable=true
        env:
          token: ${{ secrets.token }}
          RP_TOKEN: ${{ secrets.RP_TOKEN }}

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: build/reports/tests/

      # Finish Test Run Notification
      - name: Finish Test Run Notification
        uses: FreEZer00/teams-webhook-action@v1.4.1
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: 'API tests run finished'
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          additional_button_title: |-
            Link to all runs
            Link to RP
          additional_button_url: |-
            https://github.com/PolinaPanarina/ATMPA/actions/workflows/runApiTests.yml
            https://reportportal.epam.com/ui/#polina_panarina_personal_1/launches/all
